### ISSUE TITLE
Custom Recipe mit Verzauberung(Tools) als Ergebnis

### ISSUE THREAD

**Issue by MrSquid1yt** [Coding-Schule/Pocketmine-Tutorials#10]

**Comment by champmq** [comment]
Also eig gibts nh description um zu schreiben was man genau will und der Titel hilft zur Orientierung

**Comment by HimmelKreis4865** [comment]
Dies ist in PocketMine-MP unmöglich. Ob es in API4 anders ist wage ich zu bezweifeln.

Verzauberungen, Loren, Customnames sind mit NBT in MCBE nicht möglich (stand 1.16) daher ist das unmöglich.
