### ISSUE TITLE
Objektorientierung.md

### ISSUE THREAD

**Issue by justinb1617** [Coding-Schule/Pocketmine-Tutorials#11]
Müssen Klassen, die man mit extends benutzen möchte, nicht abstract sein? Also 
abstract class KLASSEN_NAME {}

**Comment by NullPointer-Nico-zz** [comment]
Yea soweit ich weiß müssen dir abstract sein aber kann mich auch irren.

**Comment by r3pt1s** [comment]
Nein müssen nie nicht.
