### ISSUE TITLE
Scoreboard API

### ISSUE THREAD

**Issue by RexZetronYT23** [Coding-Schule/Pocketmine-Tutorials#3]
Macht pls nen Tutorial rein für die scoreboard api oder wie man ohne scoreboard api ein scoreboard machen kann

**Comment by ChampOfGames** [comment]
Diesen Vorschlag gab es schon siehe [Issue 1](https://github.com/Coding-Schule/Pocketmine-Tutorials/issues/3) daher werde ich das hier schließen.
